output_path: data/youtube_out/
client_json_file: data/secrets/client_secrets.json
video_format: 18
s3_bucket: splitframe-out
frame_interval: 2
playlist_id: PLNP_nRm4k4jdEQ-OM31xNqeE64svvx-aT
video_range_keep: 52-60
video_range_train:
video_range_test: 61-62