output_path: /media/diego/QData/youtube_out/
client_json_file: /media/diego/QData/secrets/client_secrets.json
video_format: 18
s3_bucket: splitframe-out
frame_interval: 2
playlist_id: PLNP_nRm4k4jdEQ-OM31xNqeE64svvx-aT
video_range: